library(RGtk2)
win <- gtkWindow()

vbox <- gtkVBox(FALSE, 5)
win$add(vbox)

homo <- gtkFrame("homogeneous=TRUE")
vbox$packStart(homo, FALSE, FALSE)

hetero <- gtkFrame("homogeneous=FALSE")
vbox$packStart(hetero, FALSE, FALSE)

vbox <- gtkVBox(FALSE, 5)
vbox$setBorderWidth(5)
homo$add(vbox)

# for placing a numeric label next to the row
nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("1"), FALSE, FALSE)
hbox <- gtkHBox(TRUE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("fill=FALSE"), fill = FALSE)
hbox$packStart(gtkButton("fill=FALSE"), fill = FALSE)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("2"), FALSE, FALSE)
hbox <- gtkHBox(TRUE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("fill=TRUE"), fill = TRUE)
hbox$packStart(gtkButton("fill=FALSE"), fill = FALSE)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("3"), FALSE, FALSE)
hbox <- gtkHBox(TRUE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("fill=TRUE"), fill = TRUE)
hbox$packStart(gtkButton("fill=TRUE"), fill = TRUE)

vbox <- gtkVBox(FALSE, 5)
vbox$setBorderWidth(5)
hetero$add(vbox)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("4"), FALSE, FALSE)
hbox <- gtkHBox(FALSE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("expand=TRUE, fill=FALSE"), TRUE, FALSE)
hbox$packStart(gtkButton("expand=TRUE, fill=FALSE"), TRUE, FALSE)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("5"), FALSE, FALSE)
hbox <- gtkHBox(FALSE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("expand=FALSE, fill=FALSE"), FALSE, FALSE)
hbox$packStart(gtkButton("expand=FALSE, fill=FALSE"), FALSE, FALSE)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("6"), FALSE, FALSE)
hbox <- gtkHBox(FALSE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("expand=TRUE, fill=FALSE"), TRUE, FALSE)
hbox$packStart(gtkButton("expand=FALSE, fill=FALSE"), FALSE, FALSE)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("7"), FALSE, FALSE)
hbox <- gtkHBox(FALSE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("expand=TRUE, fill=TRUE"), TRUE, TRUE)
hbox$packStart(gtkButton("expand=FALSE, fill=FALSE"), FALSE, FALSE)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("8"), FALSE, FALSE)
hbox <- gtkHBox(FALSE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("expand=TRUE, fill=TRUE"), TRUE, TRUE)
hbox$packStart(gtkButton("expand=TRUE, fill=FALSE"), TRUE, FALSE)

nbox <- gtkHBox(FALSE, 5)
nbox$packStart(gtkLabel("9"), FALSE, FALSE)
hbox <- gtkHBox(FALSE, 5)
nbox$add(hbox)
vbox$packStart(nbox, FALSE, FALSE)
hbox$packStart(gtkButton("expand=TRUE, fill=TRUE"), TRUE, TRUE)
hbox$packStart(gtkButton("expand=TRUE, fill=TRUE"), TRUE, TRUE)

