GtkMozEmbedProgressFlags<-c("start" = 1,
	"redirecting" = 2,
	"transferring" = 4,
	"negotiating" = 8,
	"stop" = 16,
	"is-request" = 65536,
	"is-document" = 131072,
	"is-network" = 262144,
	"is-window" = 524288)
storage.mode(GtkMozEmbedProgressFlags) <- 'numeric'
class(GtkMozEmbedProgressFlags) <- 'enums'
.GtkMozEmbedProgressFlags<-c("GTK_MOZ_EMBED_FLAG_START" = 1,
	"GTK_MOZ_EMBED_FLAG_REDIRECTING" = 2,
	"GTK_MOZ_EMBED_FLAG_TRANSFERRING" = 4,
	"GTK_MOZ_EMBED_FLAG_NEGOTIATING" = 8,
	"GTK_MOZ_EMBED_FLAG_STOP" = 16,
	"GTK_MOZ_EMBED_FLAG_IS_REQUEST" = 65536,
	"GTK_MOZ_EMBED_FLAG_IS_DOCUMENT" = 131072,
	"GTK_MOZ_EMBED_FLAG_IS_NETWORK" = 262144,
	"GTK_MOZ_EMBED_FLAG_IS_WINDOW" = 524288)
storage.mode(.GtkMozEmbedProgressFlags) <- 'numeric'
class(.GtkMozEmbedProgressFlags) <- 'enums' 

GtkMozEmbedStatusFlags<-c("dns" = 2152398878,
	"connect" = 2152398861,
	"timeout" = 2152398862,
	"usercanceled" = 2152398850)
storage.mode(GtkMozEmbedStatusFlags) <- 'numeric'
class(GtkMozEmbedStatusFlags) <- 'enums'
.GtkMozEmbedStatusFlags<-c("GTK_MOZ_EMBED_STATUS_FAILED_DNS" = 2152398878,
	"GTK_MOZ_EMBED_STATUS_FAILED_CONNECT" = 2152398861,
	"GTK_MOZ_EMBED_STATUS_FAILED_TIMEOUT" = 2152398862,
	"GTK_MOZ_EMBED_STATUS_FAILED_USERCANCELED" = 2152398850)
storage.mode(.GtkMozEmbedStatusFlags) <- 'numeric'
class(.GtkMozEmbedStatusFlags) <- 'enums' 

GtkMozEmbedReloadFlags<-c("normal" = 1,
	"bypasscache" = 2,
	"bypassproxy" = 4,
	"bypassproxyandcache" = 8,
	"charsetchange" = 16)
storage.mode(GtkMozEmbedReloadFlags) <- 'numeric'
class(GtkMozEmbedReloadFlags) <- 'enums'
.GtkMozEmbedReloadFlags<-c("GTK_MOZ_EMBED_FLAG_RELOADNORMAL" = 1,
	"GTK_MOZ_EMBED_FLAG_RELOADBYPASSCACHE" = 2,
	"GTK_MOZ_EMBED_FLAG_RELOADBYPASSPROXY" = 4,
	"GTK_MOZ_EMBED_FLAG_RELOADBYPASSPROXYANDCACHE" = 8,
	"GTK_MOZ_EMBED_FLAG_RELOADCHARSETCHANGE" = 16)
storage.mode(.GtkMozEmbedReloadFlags) <- 'numeric'
class(.GtkMozEmbedReloadFlags) <- 'enums' 

GtkMozEmbedChromeFlags<-c("defaultchrome" = 1,
	"windowborderson" = 2,
	"windowcloseon" = 4,
	"windowresizeon" = 8,
	"menubaron" = 16,
	"toolbaron" = 32,
	"locationbaron" = 64,
	"statusbaron" = 128,
	"personaltoolbaron" = 256,
	"scrollbarson" = 512,
	"titlebaron" = 1024,
	"extrachromeon" = 2048,
	"allchrome" = 4096,
	"windowraised" = 33554432,
	"windowlowered" = 67108864,
	"centerscreen" = 134217728,
	"dependent" = 268435456,
	"modal" = 536870912,
	"openasdialog" = 1073741824,
	"openaschrome" = 2147483648)
storage.mode(GtkMozEmbedChromeFlags) <- 'numeric'
class(GtkMozEmbedChromeFlags) <- 'enums'
.GtkMozEmbedChromeFlags<-c("GTK_MOZ_EMBED_FLAG_DEFAULTCHROME" = 1,
	"GTK_MOZ_EMBED_FLAG_WINDOWBORDERSON" = 2,
	"GTK_MOZ_EMBED_FLAG_WINDOWCLOSEON" = 4,
	"GTK_MOZ_EMBED_FLAG_WINDOWRESIZEON" = 8,
	"GTK_MOZ_EMBED_FLAG_MENUBARON" = 16,
	"GTK_MOZ_EMBED_FLAG_TOOLBARON" = 32,
	"GTK_MOZ_EMBED_FLAG_LOCATIONBARON" = 64,
	"GTK_MOZ_EMBED_FLAG_STATUSBARON" = 128,
	"GTK_MOZ_EMBED_FLAG_PERSONALTOOLBARON" = 256,
	"GTK_MOZ_EMBED_FLAG_SCROLLBARSON" = 512,
	"GTK_MOZ_EMBED_FLAG_TITLEBARON" = 1024,
	"GTK_MOZ_EMBED_FLAG_EXTRACHROMEON" = 2048,
	"GTK_MOZ_EMBED_FLAG_ALLCHROME" = 4096,
	"GTK_MOZ_EMBED_FLAG_WINDOWRAISED" = 33554432,
	"GTK_MOZ_EMBED_FLAG_WINDOWLOWERED" = 67108864,
	"GTK_MOZ_EMBED_FLAG_CENTERSCREEN" = 134217728,
	"GTK_MOZ_EMBED_FLAG_DEPENDENT" = 268435456,
	"GTK_MOZ_EMBED_FLAG_MODAL" = 536870912,
	"GTK_MOZ_EMBED_FLAG_OPENASDIALOG" = 1073741824,
	"GTK_MOZ_EMBED_FLAG_OPENASCHROME" = 2147483648)
storage.mode(.GtkMozEmbedChromeFlags) <- 'numeric'
class(.GtkMozEmbedChromeFlags) <- 'enums' 

