This example illustrates how the basic widgets can be combined to make
a dialog for gathering information to run a $t$-test. A realization is shown in Figure~\ref{fig:fig-tcltk-t-test}.

\begin{figure}
  \centering
  \includegraphics[width=.75\textwidth]{fig-tcltk-t-test.png}
  \caption{A dialog to collect values for a $t$ test.}
  \label{fig:fig-tcltk-t-test}
\end{figure}

<<echo=FALSE>>=
## t.test dialog
## using basic widgets -- no entry widgets yet
library(tcltk)
@ 

<<echo=FALSE>>=
## helper functions
## not shown
getDfs <- function(envir=.GlobalEnv) {
  tmp <- ls(envir=envir)
  out <- sapply(tmp, function(i) is.data.frame(get(i, envir=envir)))
  tmp[out]
}
getNumericVars <- function(df) {
  if(missing(df))
    return(c(""))
  nms <- names(df)
  ind <- sapply(df, is.numeric)
  if(length(ind) > 0)
    nms[ind]
  else
    c("")
}
getTwoLevelFactor <- function(df) {
  if(missing(df))
    return(c(""))
  nms <- names(df)
  ind <- sapply(df, function(i) length(levels(as.factor(i))) == 2)
  if(length(ind) > 0)
    nms[ind]
  else
    c("")
}
@ 



We will use a data store to hold the values to be passed to
\code{t.test}. For the data store, we  use an environment to hold \Tcl\/ variables.

<<dataModel>>=
### Data model
e <- new.env()
e$x <- tclVar(""); e$f <- tclVar(""); e$data <- tclVar("")
e$mu <- tclVar(0); e$alternative <- tclVar("two.sided")
e$conf.level <- tclVar(95); e$var.equal <- tclVar(FALSE)
@ 


<<notShown, echo=FALSE>>=
### GUI Our standard setup
w <- tktoplevel()
tkwm.title(w, "t-test Dialog")
f <- ttkframe(w, padding=c(3,3,3,12))
tkpack(f, expand=TRUE, fill="both")
@ 

Our layout is basic. Here we pack a label frame into the window to give the dialog a nicer look.
We will use the \code{tkgrid} geometry manager below.
<<layout>>=
lf <- ttklabelframe(f, text="t.test()", padding=10)
tkpack(lf, expand=TRUE, fill="both", padx=5, pady=5)
@ 


This next function simplifies the task of adding a label.


<<tkgridHelper>>=
putLabel <- function(parent, text, row, column) {
  label <- ttklabel(parent, text=text)
  tkgrid(label, row=row, column=column, sticky="e")
}
@ 

Our first widget will be one to select a data frame. For this, a
combobox is used, although if a large number of data frames are a
possibility, a different widget may be better suited. The
\code{getDfs} function is not shown, but simply returns the names of
all data frames in the global environment. Also not shown are two
similar calls to create comboboxes \code{xCombo} and \code{fCombo}
which allow the user to specify parts of a formula.

<<>>=
putLabel(lf, "data:",0,0)
dataCombo <- ttkcombobox(lf, values=getDfs(), textvariable=e$data)
tkgrid(dataCombo, row=0, column=1, sticky="ew", padx=2)
tkfocus(dataCombo)                      # give focus
@ 

<<notShown, echo=FALSE>>=
## not shown
putLabel(lf, "x:",1,0)
xCombo <-  ttkcombobox(lf, values=getNumericVars(), textvariable=e$x)
tkgrid(xCombo, row=1, column=1, sticky="ew", padx=2)
@ 

<<notShown, echo=FALSE>>=
## not shown
putLabel(lf, "~ f:",1,2)
fCombo <-  ttkcombobox(lf, values=getTwoLevelFactor(), textvariable=e$f)
tkgrid(fCombo, row=1, column=3, sticky="ew", padx=2)
@ 

The combobox may not be the most natural widget to gather a numeric
value for the mean when the data is continuous, but at this point we
haven't quite yet discussed the \code{ttkentry} widget.
<<mu>>=
putLabel(lf, "mu:", 2, 0)
muCombo <-  ttkcombobox(lf, values=c(""), textvariable=e$mu)
tkgrid(muCombo, row=2, column=1, sticky="ew", padx=2)
@ 

The selection of an alternative hypothesis is a natural choice for a
combo box, but, as this alternative is available in \pkg{tcltk}, we
use a spin box with \code{wrap=TRUE}.
<<echo=FALSE>>=
ttkscale <- function(parent, ...) tkwidget(parent, "ttk::scale", ...)
tkspinbox <- function(parent, ...) tkwidget(parent, "tk::spinbox", ...)
@ 
<<>>=
putLabel(lf, "alternative:", 3, 0)
altCombo <- tkspinbox(lf, values=c("two.sided","less","greater"),
                      textvariable=e$alternative, wrap=TRUE)
tkgrid(altCombo, row=3, column=1, sticky="ew", padx=2)
@ 

Here we use two widgets to specify the confidence level. The slider
is quicker to use, but less precise than the spinbox. By sharing a
text variable, the widgets are automatically synchronized.
<<>>=
putLabel(lf, "conf.level:", 3, 2)
altFrame <- ttkframe(lf)
tkgrid(altFrame, row=3, column=3, columnspan=2, 
       sticky="ew", padx=2)
altScale <- ttkscale(altFrame, from=75, to=100, 
                     variable=e$conf.level)
tkpack(altScale, expand=TRUE, fill="y", side="left")

altSpin <- tkspinbox(altFrame, from=75, to=100, increment=1, 
                     textvariable=e$conf.level, width=5)
tkpack(altSpin, side="left")
@ 

A checkbox is used to set the binary variable for \code{var.equal}
<<>>=
putLabel(lf, "var.equal:", 4, 0)
veCheck <- ttkcheckbutton(lf, variable=e$var.equal)
tkgrid(veCheck, row=4, column=1, stick="w", padx=2)
@ 

When assigning grid weights, we don't want the labels (columns 0 and 2) to expand the same way we want the other columns to do, so we assign different weights.
<<>>=
tkgrid.columnconfigure(lf, 0, weight=1)
tkgrid.columnconfigure(lf, 1, weight=10)
tkgrid.columnconfigure(lf, 2, weight=1)
tkgrid.columnconfigure(lf, 1, weight=10)
@ 

The dialog has two control buttons we wish to include.
<<>>=
bf <- ttkframe(f)
tkpack(bf, fill="x", padx=5, pady=5)

cancel <- ttkbutton(bf, text="cancel", command=function() {
  tcl("after","cancel",updateID$ID)
  tkdestroy(w)
})
ok <- ttkbutton(bf, text="ok")

tkpack(ttklabel(bf, text=" "), expand=TRUE, fill="y", 
       side="left")                     # add a spring
tkpack(cancel, padx=6, side="left")
tkpack(ok, padx=6, side="left")
tkconfigure(ok, default="active")
@ 

The \code{ok} button is made to look active. As such we should bind to the button click and \qcode{Return} signals. First we define the callback. The \code{runTTest} function is not shown, but is written to make good use of the structure of the data store.
<<>>=
okCallback <- function() {
  l <- lapply(e, tclvalue)
  runTTest(l)
}
tkbind(ok, "<Button-1>", okCallback)
tkbind(w, "<Return>", okCallback)        # for active binding
@ 

At this point, our GUI is complete, but we would like to have it
reflect any changes to the underlying \R\/ environment that effect its
display. A such, we define
a function, \code{updateUI}, which does two basic things: it searches for
new data frames and it adjusts the controls depending on the current
state.
<<>>=
updateUI <- function() {
  tkconfigure(dataCombo, values=getDfs())
  dfName <- tclvalue(e$data)

  if(dfName == "") {
    tkconfigure(xCombo, state="disabled")
  } else {
    df <- get(dfName, envir=.GlobalEnv)
    tkconfigure(xCombo, state="normal", values=getNumericVars(df))
    if(! tclvalue(e$x) %in% getNumericVars(df))
      tclvalue(e$x) <- ""

    tkconfigure(fCombo, values=getTwoLevelFactor(df))
    if(!tclvalue(e$f) %in% getTwoLevelFactor(df))
      tclvalue(e$f) <- ""
  }
  
  tkconfigure(fCombo, state=
              ifelse(tclvalue(e$x) == "", "disabled", "normal"))
  
  if(tclvalue(e$f) == "")  {
    tkconfigure(muCombo, state="normal")
    tkconfigure(veCheck, state="disabled")
  } else {
    tclvalue(e$mu) <- 0
    tkconfigure(muCombo, state="disabled")
    tkconfigure(veCheck, state="normal")
  }
}
@ 

We use the \code{after} command to repeat a function call every so often. We also define a flag to stop the polling if desired. When polling, we make sure to test for existence of the parent window. 
<<>>=
updateID <- new.env()
updateID$flag <- TRUE
updateID$ID <- NA
repeatFun <- function() {
  if(updateID$flag && as.logical(tkwinfo("exists",w))) {
    updateUI()
    updateID$ID <- tcl("after", 1000, repeatFun)
  }
}
repeatFun()
@ 
% <<>>=
% updateUI()                              # run once
% tkbind("TCombobox","<<ComboboxSelected>>", updateUI) ## misses update on new data
% @ 

<<echo=FALSE>>=
## We don't show the function runTTest.
## It is a bit long, as care must be taken as it isn't clear if a formula should be used.  
runTTest <- function(l) {
  ## ugly function to run t test
  if(l$data == "" || l$x == "")
    return()

  l$data <- get(l$data, envir=.GlobalEnv)

  if(l$f != "") {
    l$formula <- formula(paste(l$x,l$f, sep="~"))
    l$x <- l$f <- NULL
    l$mu <- NULL
    l$var.equal <- as.logical(as.numeric(l$var.equal))

    TTest <- stats:::t.test.formula
  } else {
    l$x <- l$data[, l$x]
    l$f <- NULL
    l$mu = as.numeric(l$mu)
    l$var.equal <- NULL

    TTest <- stats:::t.test.default
  }
  l$conf.level <- as.numeric(l$conf.level)/100
  ret <- capture.output(do.call("TTest", l))
  cat(paste(ret, collapse="\n"))
}
@ 
