In web programming it is common to have textarea entries be validated
prior to their values being submitted. By validating ahead of time,
the programmer can avoid the lag created by communicating with the
server when the input is not acceptable. However, despite
this lag not being the case for the GUIs considered now, it may still be a
useful practice to validate the values of a text area when the
underlying handlers are expecting a specific type of value.
  
The \args{coerce.with} argument can be used to specify a function
to coerce values after an action is initiatied, but in this example we
show how to validate the text widget when it loses focus. If the value
is invalid, we set the text color to red.

<<validationExample, echo=FALSE>>=
require(gWidgets)
@

<<>>=
w <- gwindow("Validation example")
validRegexpr <- "[[:digit:]]{3}-[[:digit:]]{4}"
tbl <- glayout(cont=w)
tbl[1,1] <- "Phone number (XXX-XXXX)"
tbl[1,2] <- (e <- gedit("", cont = tbl))
tbl[2,2] <- (b <- gbutton("submit", cont = tbl, 
                          handler=function(h,...) print("hi")))
## Blur is focus out event
addHandlerBlur(e, handler = function(h,...) {
  curVal <- svalue(h$obj)
  if(grepl(validRegexpr, curVal)) {
    font(h$obj) <- c(color="black")
  } else {
    font(h$obj) <- c(color="red")
    focus(h$obj) <- TRUE
  }
})
@ 
