  In web programming, it is common to have text area entries validated
  prior to their values being submitted. This arose out of the lag
  created while a web page communicates with a server. However,
  despite this not being the case for the GUIs considered now, it may
  still be a useful practice to validate the values of a text area
  when the underling handlers are expecting a specific type of value.
  
  Now the \args{coerce.with} argument can be used to specify a
  function to coerce values after an action is initiatied, but in this
  example we show how to 
